backend: import github.com/oapi-codegen/echo-middleware
Replace github.com/deepmap/oapi-codegen/pkg/middleware with
github.com/oapi-codegen/echo-middleware in pkg/server/server.go,
to fix golangci-lint errors with oapi-codegen 1.16+ like:

```
./tools/golangci-lint run --fix
Error: pkg/server/server.go:108:8: SA1019: oapimiddleware.OapiRequestValidatorWithOptions
is deprecated: This has been replaced by
https://pkg.go.dev/github.com/oapi-codegen/echo-middleware#OapiRequestValidatorWithOptions
(staticcheck)
    e.Use(oapimiddleware.OapiRequestValidatorWithOptions(swagger,
    &oapimiddleware.Options{Options:
    openapi3filter.Options{AuthenticationFunc: nebraskaAuthenticationFunc(conf.AuthMode)},
    Skipper: middlewareSkipper}))
```